[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "tay-client"
version = "0.9.4"
description = "Python SDK for producing and executing Tay jobs"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name = "Andrii Sydorenko"}]
keywords = ["background-jobs", "job-queue", "scheduler", "unix-socket"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: MacOS",
  "Operating System :: POSIX",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

[project.urls]
Documentation = "https://github.com/AndriiSydorenko1904/tay/tree/v0.9.4/clients/python"
Issues = "https://github.com/AndriiSydorenko1904/tay/issues"
Source = "https://github.com/AndriiSydorenko1904/tay"

[project.scripts]
tay-worker = "tay.__main__:main"

[tool.setuptools]
packages = ["tay"]

[tool.setuptools.package-data]
tay = ["py.typed"]
